# frozen_string_literal: true

require "bundler/gem_tasks"
Bundler::GemHelper.tag_prefix = "omq-lz4-"

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs   << "test"
  t.libs   << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.verbose = true
end

task default: :test
