# frozen_string_literal: true

source "https://rubygems.org"

if RUBY_ENGINE == "jruby"
  gemspec glob: "omq-backend-rust-java.gemspec"
else
  gemspec glob: "omq-backend-rust.gemspec"
end

ROOT     = File.expand_path("../..", __dir__)
SIBLINGS = File.expand_path("../../..", __dir__)

gem "omq",           path: ROOT
gem "omq-rs",        path: ENV["OMQ_RS_PATH"]
gem "protocol-zmtp", path: File.join(ROOT, "gems/protocol-zmtp")
gem "nuckle",        path: ENV["OMQ_DEV"] ? File.join(SIBLINGS, "nuckle") : nil

gem "minitest"
gem "rake"
