# frozen_string_literal: true

require "bundler/gem_tasks"
Bundler::GemHelper.tag_prefix = "omq-qos-"

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
end

task default: :test
