# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "minitest"
gem "rake"
gem "localhost"

ROOT     = File.expand_path("../..", __dir__)
SIBLINGS = File.expand_path("../../..", __dir__)

gem "omq",           path: ENV["OMQ_DEV"] ? ROOT : nil
gem "protocol-zmtp", path: ENV["OMQ_DEV"] ? File.join(SIBLINGS, "protocol-zmtp") : nil
