# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "minitest"
gem "rake"
gem "localhost"

ROOT     = File.expand_path("../..", __dir__)

gem "omq",           path: ROOT
gem "protocol-zmtp", path: File.join(ROOT, "gems/protocol-zmtp")
