# frozen_string_literal: true

require "rake/testtask"
require "rake/clean"
CLOBBER.include "pkg"

require "bundler/gem_helper"
Bundler::GemHelper.new.tap do |gem_helper|
  gem_helper.tag_prefix = "protocol-zmtp-"
  gem_helper.install
end

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task default: :test
